In [ ]:
import numpy as np
#creating Arrays
arr=np.array([1,2,3,4,5],dtype=float)
print(arr)


[1. 2. 3. 4. 5.]


In [ ]:
#creating matrix using zeros
zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#array manipulation
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [ ]:
#arange function
arange_arr=np.arange(10)
print(arange_arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#slicing the array
sliced_arr=arr[2:4]
print(sliced_arr)

[3. 4.]


In [ ]:
#transpose of the array
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.T
print(b)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
#matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
#linear algebra.eigen value
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
# saving file to my drivre
data=np.loadtxt("/content/drive/MyDrive/Data Set/SOC.txt.txt",dtype=int)
d=np.savetxt("/content/SOC.txt.txt",data)
print(d)
print(data)

None
[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 3 5 7 9]
 [2 4 6 8 0]
 [1 4 7 0 5]]


In [ ]:
#arange function(starting,ending,b/w range)
arange=np.arange(0,1000,5)
print(arange)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
# saving output of above file into .txt file
m=np.savetxt("/content/arrang.txt",arange)
data1=np.loadtxt("/content/arrang.txt",dtype=int)
print(data1)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


<ipython-input-12-b2828d8c1714>:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  data1=np.loadtxt("/content/arrang.txt",dtype=int)


In [ ]:
#random function
r=np.random.rand()
print(r)
s=np.random.randint(0,2)
print(s)

0.9024073806953714
1


In [ ]:
#type,shape and dimension
a=np.array([[2,3],[5,6]])
print(type(a))
print(a.ndim)
print(a.shape)


<class 'numpy.ndarray'>
2
(2, 2)


In [ ]:
# (starting,ending,varrying)of linspace funtion
b=np.linspace(0.8,2,5)
print(b)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
#.split function
b=np.split(a,4)
print(b)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
#reshape function(set,row,column)
q=np.arange(24).reshape(6,1,4)
print(q)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]

 [[12 13 14 15]]

 [[16 17 18 19]]

 [[20 21 22 23]]]


In [ ]:
#a*b=element,(a@b/a.b)=matrix multiplication
i=np.array([[2,3],[5,6]])
j=np.array([[2,3],[5,6]])
print(i*j)
print(i@j)
k=np.dot(i,j)
print(k)

[[ 4  9]
 [25 36]]
[[19 24]
 [40 51]]
[[19 24]
 [40 51]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
#.sum function//total sum of matrix
print(a.sum())
#.sum(axis=1)//row wise addition
print(a.sum(axis=1))
#.sum(axis=0)//column wise addition
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
[3 3]
[2 2 2]


In [ ]:
a=np.floor(np.random.random((2,12)))
b=np.ceil(np.random.random((2,12)))
c=np.random.random((2,2))
print(a)
print(c)
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0.77370898 0.69319416]
 [0.78462337 0.32683524]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
#.max function//max value in matrix
print(a.max())
#.max(axis=1)//row wise max values
print(a.max(axis=1))
#.max(axis=0)//column wise max values
print(a.max(axis=0))

[[1 1 1]
 [1 1 1]]
1
[1 1]
[1 1 1]


In [ ]:
a=np.array([[2,3],[4,5]])
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
print(a.cumsum(axis=1))

5
[3 5]
[4 5]
[[2 5]
 [4 9]]


In [ ]:
a=np.array([[2,3,4,5,6,7]])
print(a.cumsum(axis=1))
a.resize([3,2])
print(a)
print(a.shape)

[[ 2  5  9 14 20 27]]
[[2 3]
 [4 5]
 [6 7]]
(3, 2)


In [ ]:
#joining two array using vstack(vertical stacking),hstack(horizontal stacking)
a=np.array([[2,3,4,5,6,7]])
a.resize([2,3])
print(a)
b=np.array([[6,5,9,2,4,5]])
b.resize([2,3])
print(b)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[2 3 4]
 [5 6 7]]
[[6 5 9]
 [2 4 5]]
[[2 3 4]
 [5 6 7]
 [6 5 9]
 [2 4 5]]
[[2 3 4 6 5 9]
 [5 6 7 2 4 5]]


In [ ]:
#dstack(col,set,row),actual=set,row,col)
a=np.arange(0,30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
v=10
print(type(v))

<class 'int'>


In [ ]:
print("hello world",end=' ')
print("hello world")

hello world hello world


In [ ]:
l=[1,2,3,4,5]
print(len(l))

5


In [ ]:
l=[1,2,3,4,5]
print(l[2])

3


In [ ]:
l=[1,2,3,4]
print(l.index(3))

2


In [ ]:
#eye function(prints 1 diagnally and remaing all zeros)
a1=np.eye(4)
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#full and item size(prints same element in the given dimension array)
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
#asarray function(converting into arraywhich is symmetric)
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#inner(sum of row multplication(1*2+4*2+0*1)),outer(each element in first row multiplied with 2nd row elements(1*2,1*2,1*1)),cross(array chaned to column and applying dot product)
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
# rint function(more than .5 it will give next number of before point(2.8=3))
a=np.array([1.7,2.2,3.9,4.2,5.8,6.2,7.2])
np.rint(a)

array([2., 2., 4., 4., 6., 6., 7.])

In [ ]:
#true_division a/b division (1/3 ...2/4)
a=np.array([1,2])
b=np.array([3,4])
np.true_divide(a,b)

array([0.33333333, 0.5       ])

In [ ]:
#unique function (remove repeated elements)
a=np.array([1,1,2,2,3,3,4,4])
np.unique(a)

array([1, 2, 3, 4])

In [ ]:
#union1d function (remove repeted elements and prints arrays in one dimensional array)
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#interst1d function(prints only common elements)
a=np.array([[1,2],[3,4]])
b=np.array([[5,2],[7,3]])
np.intersect1d(a,b)

array([2, 3])

In [ ]:
#setdiff1d function(which is present in arr1 but not in arr2)
a=np.array([[1,2],[3,4]])
b=np.array([[5,2],[7,3]])
np.setdiff1d(a,b)

array([1, 4])

In [ ]:
#hypotenues formula
a=8
b=6
c=np.hypot(a,b)

In [ ]:
#sin function
x=np.sin(0)
print(x)

0.0


In [ ]:
#divmod function(1st array=floor quotient,2nd array=remainder)
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)

(array([ 0,  0, 15,  2,  2,  2]), array([10, 20,  0,  0,  0, 10]))


In [ ]:
#mod function(gives only remainder)
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.mod(a,b)
print(c)

[10 20  0  0  0 10]


In [ ]:
#divide function(gives only quotient(exact answer))
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)

[ 0.5         0.95238095 15.          2.          2.          2.4       ]


In [ ]:
#multiply function(element multiplication))
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)

[ 200  420   60  800 1250 1500]


In [ ]:
#matmul function
a=np.array([10,20,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.matmul(a,b)
print(c)

4230


In [ ]:
#random values of 2/3 matrix
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[ 1.55885577 -0.62280824  0.27109384]
 [-2.49463733 -1.14617061  0.15741274]]


In [ ]:
#loc=mean value,scale=standard deviation value
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[-0.46562185  2.38591767  0.45280068]
 [ 2.36154815 -3.26357514  0.87162125]]


In [ ]:
#n=total trials,p=probability
x=random.binomial(n=12,p=0.5,size=(10))
print(x)

[7 8 7 5 1 8 8 6 7 5]


In [ ]:
#lam=lamda,poisson function
x=random.poisson(lam=2,size=(10))
print(x)

[1 5 2 2 2 2 4 3 3 0]


In [ ]:
x=random.choice([1,2,3,4])
print(x)

3


In [ ]:
#p=probability,size=matrix size(3/5)
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[3 3 5 3 5]
 [5 5 5 3 5]
 [3 3 5 3 5]]


mean=(sum of elements)/total no of elements
median=middle value
varience=(sum of (each element-mean)2/total no of elements
standard deviation=sqrt(varience)

1 2 (4*1)-(0*2)
4 2 (1*1)-(2*0)
0 1 (1*2)-(4*2)

1.number of rows become no of set
2.column become rows
3.set become column